name: Scheduled Performance Testing

on:
  schedule:
    # Trigger @ 5 min intervals
    - cron:  '*/5 * * * *'

jobs:
  jmeter-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'zulu'
    - name: Build with Gradle
      run:  |
        echo "TODO 1 - create test plan"
        echo "TODO 2 - upload to BlazeMeter"
        echo "TODO 3 - Find a callback mechanism for retrieving results"
