# Release workflow
name: Release workflow

# trigger - runs on any commit tag beginning with 'v'
on:
  push:
    tags:
      - "v*"

jobs:
  build-project:
    name: Build Java Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/libs/*

  release-project:
    name: Create Application Release
    runs-on: "ubuntu-latest"
    needs: build-project
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
      - name: Create Release
        uses: actions/create-release@v1
        id: create_new_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} # v${{ github.run-number }}
      - name: Set Project Artifact Name
        run: echo "RELEASE_ARTIFACT_NAME=insight-web" >> $GITHUB_ENV
        shell: bash
      - name: Upload Artifacts to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_new_release.outputs.upload_url }} #https://docs.github.com/en/actions/learn-github-actions/environment-variables
          asset_path: ./${{ env.RELEASE_ARTIFACT_NAME }}.jar
          asset_name: ${{ env.RELEASE_ARTIFACT_NAME }}.jar
          asset_content_type: application/java-archive
