name: Remove old artifacts

on:
  schedule:
    # Every 1st day of the month @ 11 pm
    - cron: '0 23 * * *'

#on:
#  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]



jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 month'
          # Optional inputs
          # skip-tags: true
          # skip-recent: 5
